- hosts: remote
  gather_facts: false
  become: true
  become_user: root
  
  vars_promt:
    - name:      "Package_name"
      promt:    "Which package do you want to install?"
      private:  no
    - name:      "Version"
      promt:    "Which version do you want to install?"
      default:  "latest"
      private:  no
  
  tasks:
    - name:      install packages
      apt: 
        name:   "{{ Package_name }}"
        state:  "{{ Version | default('latest') }}"
